# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_language',
        ),
    ]
