from django.urls import path

from . import views

app_name = 'control_panel'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('audit/', views.AuditLogListView.as_view(), name='audit_list'),
    path('roles/', views.RoleListView.as_view(), name='role_list'),
    path('roles/create/', views.RoleCreateView.as_view(), name='role_create'),
    path('roles/<int:pk>/edit/', views.RoleUpdateView.as_view(), name='role_edit'),
    path('roles/<int:pk>/delete/', views.RoleDeleteView.as_view(), name='role_delete'),
    path('accounts/', views.AccountListView.as_view(), name='account_list'),
    path('accounts/create/', views.AccountCreateView.as_view(), name='account_create'),
    path('accounts/<int:pk>/edit/', views.AccountUpdateView.as_view(), name='account_edit'),
    path('accounts/<int:pk>/delete/', views.AccountDeleteView.as_view(), name='account_delete'),
    path('profiles/', views.UserProfileListView.as_view(), name='userprofile_list'),
    path('profiles/create/', views.UserProfileCreateView.as_view(), name='userprofile_create'),
    path('profiles/<int:pk>/edit/', views.UserProfileUpdateView.as_view(), name='userprofile_edit'),
    path('profiles/<int:pk>/delete/', views.UserProfileDeleteView.as_view(), name='userprofile_delete'),
    path('tokens/', views.AccountTokenListView.as_view(), name='accounttoken_list'),
    path('tokens/create/', views.AccountTokenCreateView.as_view(), name='accounttoken_create'),
    path('tokens/<int:pk>/edit/', views.AccountTokenUpdateView.as_view(), name='accounttoken_edit'),
    path('tokens/<int:pk>/delete/', views.AccountTokenDeleteView.as_view(), name='accounttoken_delete'),
    path('categories/', views.EquipmentCategoryListView.as_view(), name='equipmentcategory_list'),
    path('categories/create/', views.EquipmentCategoryCreateView.as_view(), name='equipmentcategory_create'),
    path('categories/<int:pk>/edit/', views.EquipmentCategoryUpdateView.as_view(), name='equipmentcategory_edit'),
    path('categories/<int:pk>/delete/', views.EquipmentCategoryDeleteView.as_view(), name='equipmentcategory_delete'),
    path('manufacturers/', views.ManufacturerListView.as_view(), name='manufacturer_list'),
    path('manufacturers/create/', views.ManufacturerCreateView.as_view(), name='manufacturer_create'),
    path('manufacturers/<int:pk>/edit/', views.ManufacturerUpdateView.as_view(), name='manufacturer_edit'),
    path('manufacturers/<int:pk>/delete/', views.ManufacturerDeleteView.as_view(), name='manufacturer_delete'),
    path('equipment/', views.EquipmentListView.as_view(), name='equipment_list'),
    path('equipment/create/', views.EquipmentCreateView.as_view(), name='equipment_create'),
    path('equipment/<int:pk>/edit/', views.EquipmentUpdateView.as_view(), name='equipment_edit'),
    path('equipment/<int:pk>/delete/', views.EquipmentDeleteView.as_view(), name='equipment_delete'),
    path('companies/', views.CompanyListView.as_view(), name='company_list'),
    path('companies/create/', views.CompanyCreateView.as_view(), name='company_create'),
    path('companies/<int:pk>/edit/', views.CompanyUpdateView.as_view(), name='company_edit'),
    path('companies/<int:pk>/delete/', views.CompanyDeleteView.as_view(), name='company_delete'),
    path('company-contacts/', views.CompanyContactListView.as_view(), name='companycontact_list'),
    path('company-contacts/create/', views.CompanyContactCreateView.as_view(), name='companycontact_create'),
    path('company-contacts/<int:pk>/edit/', views.CompanyContactUpdateView.as_view(), name='companycontact_edit'),
    path('company-contacts/<int:pk>/delete/', views.CompanyContactDeleteView.as_view(), name='companycontact_delete'),
    path('contracts/', views.LeaseContractListView.as_view(), name='leasecontract_list'),
    path('contracts/create/', views.LeaseContractCreateView.as_view(), name='leasecontract_create'),
    path('contracts/<int:pk>/edit/', views.LeaseContractUpdateView.as_view(), name='leasecontract_edit'),
    path('contracts/<int:pk>/delete/', views.LeaseContractDeleteView.as_view(), name='leasecontract_delete'),
    path('payments/', views.PaymentScheduleListView.as_view(), name='paymentschedule_list'),
    path('payments/create/', views.PaymentScheduleCreateView.as_view(), name='paymentschedule_create'),
    path('payments/<int:pk>/edit/', views.PaymentScheduleUpdateView.as_view(), name='paymentschedule_edit'),
    path('payments/<int:pk>/delete/', views.PaymentScheduleDeleteView.as_view(), name='paymentschedule_delete'),
    path('maintenance/', views.MaintenanceListView.as_view(), name='maintenance_list'),
    path('maintenance/create/', views.MaintenanceCreateView.as_view(), name='maintenance_create'),
    path('maintenance/<int:pk>/edit/', views.MaintenanceUpdateView.as_view(), name='maintenance_edit'),
    path('maintenance/<int:pk>/delete/', views.MaintenanceDeleteView.as_view(), name='maintenance_delete'),
    path('maintenance-requests/', views.MaintenanceRequestListView.as_view(), name='maintenancerequest_list'),
    path('maintenance-requests/create/', views.MaintenanceRequestCreateView.as_view(), name='maintenancerequest_create'),
    path('maintenance-requests/<int:pk>/edit/', views.MaintenanceRequestUpdateView.as_view(), name='maintenancerequest_edit'),
    path('maintenance-requests/<int:pk>/delete/', views.MaintenanceRequestDeleteView.as_view(), name='maintenancerequest_delete'),
]
