# Generated by Django 5.2.11 on 2026-02-25 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('table_name', models.CharField(max_length=100)),
                ('record_id', models.IntegerField()),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='accounts.account')),
            ],
            options={
                'verbose_name': 'запись аудита',
                'verbose_name_plural': 'журнал аудита',
                'db_table': 'audit_log',
                'ordering': ['-performed_at'],
                'indexes': [models.Index(fields=['table_name', 'record_id'], name='idx_audit_table_record'), models.Index(fields=['performed_at'], name='idx_audit_performed_at')],
            },
        ),
    ]
