# Generated by Django 5.2.11 on 2026-02-25 07:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('inn', models.CharField(max_length=12, unique=True)),
                ('ogrn', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('bank_details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Активна'), ('blocked', 'Заблокирована'), ('pending', 'На модерации')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='accounts.account')),
            ],
            options={
                'verbose_name': 'компания',
                'verbose_name_plural': 'компании',
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='LeaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждена'), ('rejected', 'Отклонена'), ('cancelled', 'Отменена')], default='pending', max_length=50)),
                ('message', models.TextField(blank=True)),
                ('manager_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_requests', to='accounts.account')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_lease_requests', to='accounts.account')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_requests', to='catalog.equipment')),
            ],
            options={
                'verbose_name': 'заявка на лизинг',
                'verbose_name_plural': 'заявки на лизинг',
                'db_table': 'lease_request',
            },
        ),
        migrations.CreateModel(
            name='LeaseContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('lease_term_months', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('advance_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_day', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Действует'), ('completed', 'Завершён'), ('terminated', 'Расторгнут')], default='draft', max_length=50)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lease_contracts', to='leasing.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to='accounts.account')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lease_contracts', to='catalog.equipment')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_contracts', to='accounts.account')),
                ('lease_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease_contract', to='leasing.leaserequest')),
            ],
            options={
                'verbose_name': 'договор лизинга',
                'verbose_name_plural': 'договоры лизинга',
                'db_table': 'lease_contract',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='accounts.account')),
                ('lease_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='leasing.leaserequest')),
            ],
            options={
                'verbose_name': 'сообщение чата',
                'verbose_name_plural': 'сообщения чата',
                'db_table': 'chat_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('urgency', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('critical', 'Критичный')], default='normal', max_length=50)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('completed', 'Выполнена'), ('cancelled', 'Отменена')], default='new', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance_requests', to='accounts.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='leasing.company')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='catalog.equipment')),
            ],
            options={
                'verbose_name': 'заявка на обслуживание',
                'verbose_name_plural': 'заявки на обслуживание',
                'db_table': 'maintenance_request',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_chat_messages', to='accounts.account')),
                ('maintenance_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='leasing.maintenancerequest')),
            ],
            options={
                'verbose_name': 'сообщение чата ТО',
                'verbose_name_plural': 'сообщения чата ТО',
                'db_table': 'maintenance_chat_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.IntegerField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('paid', 'Оплачен'), ('overdue', 'Просрочен'), ('cancelled', 'Отменён')], default='pending', max_length=50)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedule', to='leasing.leasecontract')),
            ],
            options={
                'verbose_name': 'платёж по графику',
                'verbose_name_plural': 'графики платежей',
                'db_table': 'payment_schedule',
                'constraints': [models.UniqueConstraint(fields=('contract', 'payment_number'), name='unique_contract_payment_number')],
            },
        ),
    ]
