# Generated by Django 5.2.7 on 2026-02-20 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        ('leasing', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='LeaseRequest',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждена'), ('rejected', 'Отклонена')], default='pending', max_length=50)),
                        ('message', models.TextField(blank=True)),
                        ('manager_notes', models.TextField(blank=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_requests', to='accounts.account')),
                        ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_lease_requests', to='accounts.account')),
                        ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_requests', to='catalog.equipment')),
                    ],
                    options={
                        'verbose_name': 'заявка на лизинг',
                        'verbose_name_plural': 'заявки на лизинг',
                        'db_table': 'lease_request',
                    },
                ),
            ],
        ),
    ]
