# Generated by Django 5.2.7 on 2026-02-20 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('leasing', '0002_add_lease_request'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='ChatMessage',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('text', models.TextField()),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('lease_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='leasing.leaserequest')),
                        ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='accounts.account')),
                    ],
                    options={
                        'verbose_name': 'сообщение чата',
                        'verbose_name_plural': 'сообщения чата',
                        'db_table': 'chat_message',
                        'ordering': ['created_at'],
                    },
                ),
            ],
        ),
    ]
