# Generated by Django 5.2.11 on 2026-02-25 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'производитель',
                'verbose_name_plural': 'производители',
                'db_table': 'manufacturer',
            },
        ),
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('icon_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.equipmentcategory')),
            ],
            options={
                'verbose_name': 'категория техники',
                'verbose_name_plural': 'категории техники',
                'db_table': 'equipment_category',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=150)),
                ('specifications', models.TextField(blank=True, default='')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('vin', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('condition', models.CharField(choices=[('new', 'Новая'), ('used', 'Б/У'), ('refurbished', 'Восстановленная')], default='new', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('residual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monthly_lease_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('available', 'Доступна'), ('leased', 'В лизинге'), ('maintenance', 'На обслуживании'), ('sold', 'Продана')], default='available', max_length=50)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('images_urls', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='equipment', to='catalog.equipmentcategory')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='catalog.manufacturer')),
            ],
            options={
                'verbose_name': 'техника',
                'verbose_name_plural': 'техника',
                'db_table': 'equipment',
            },
        ),
    ]
